spring:
  application:
    name: my-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:config/
server:
  port: 0


endpoints:
  restart:
    enabled: true
