server:
  port: 0

people:
  my-value: this is from config server!!

lombok:
  anyConstructor:
    addConstructorProperties: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: testspringcloud

